openapi: 3.0.0
info:
  title: Task Management Service API
  description: API for managing tasks and workflows in Oppie.xyz system
  version: 1.0.0
  contact:
    name: Oppie.xyz Team

paths:
  /api/v1/tasks:
    get:
      summary: Get all tasks
      description: Retrieve all tasks in the system
      operationId: getAllTasks
      tags:
        - Tasks
      parameters:
        - name: status
          in: query
          description: Filter tasks by status
          required: false
          schema:
            type: string
            enum: [PENDING, IN_PROGRESS, COMPLETED, FAILED, CANCELED]
        - name: priority
          in: query
          description: Filter tasks by priority
          required: false
          schema:
            type: string
            enum: [LOW, MEDIUM, HIGH, CRITICAL]
        - name: limit
          in: query
          description: Maximum number of tasks to return
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '500':
          description: Internal server error

    post:
      summary: Create a new task
      description: Create a new task in the system
      operationId: createTask
      tags:
        - Tasks
      requestBody:
        description: Task data to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /api/v1/tasks/{taskId}:
    get:
      summary: Get task by ID
      description: Retrieve a specific task by its ID
      operationId: getTaskById
      tags:
        - Tasks
      parameters:
        - name: taskId
          in: path
          description: ID of the task to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error
          
    post:
      summary: Update task status
      description: Update the status of an existing task
      operationId: updateTaskStatus
      tags:
        - Tasks
      parameters:
        - name: taskId
          in: path
          description: ID of the task to update
          required: true
          schema:
            type: string
      requestBody:
        description: Task status update data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskStatusUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '404':
          description: Task not found
        '500':
          description: Internal server error

  /api/v1/workflows:
    get:
      summary: Get all workflows
      description: Retrieve all workflows in the system
      operationId: getAllWorkflows
      tags:
        - Workflows
      parameters:
        - name: status
          in: query
          description: Filter workflows by status
          required: false
          schema:
            type: string
            enum: [ACTIVE, PAUSED, COMPLETED, FAILED]
        - name: limit
          in: query
          description: Maximum number of workflows to return
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of workflows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workflow'
        '500':
          description: Internal server error

    post:
      summary: Create a new workflow
      description: Create a new workflow in the system
      operationId: createWorkflow
      tags:
        - Workflows
      requestBody:
        description: Workflow data to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowInput'
      responses:
        '201':
          description: Workflow created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Detailed description of the task
        status:
          type: string
          enum: [PENDING, IN_PROGRESS, COMPLETED, FAILED, CANCELED]
          description: Current status of the task
        priority:
          type: string
          enum: [LOW, MEDIUM, HIGH, CRITICAL]
          description: Priority level of the task
        workflowId:
          type: string
          description: ID of the workflow this task belongs to (if any)
        dependencies:
          type: array
          description: IDs of tasks that this task depends on
          items:
            type: string
        assignedTo:
          type: string
          description: ID of the agent assigned to this task
        executionContext:
          type: object
          description: Execution context for the task
          additionalProperties: true
        metadata:
          type: object
          description: Additional metadata for the task
          additionalProperties: true
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
      required:
        - id
        - title
        - status
        - priority
        - createdAt
        - updatedAt
          
    TaskInput:
      type: object
      properties:
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Detailed description of the task
        priority:
          type: string
          enum: [LOW, MEDIUM, HIGH, CRITICAL]
          description: Priority level of the task
        workflowId:
          type: string
          description: ID of the workflow this task belongs to (if any)
        dependencies:
          type: array
          description: IDs of tasks that this task depends on
          items:
            type: string
        assignedTo:
          type: string
          description: ID of the agent assigned to this task
        executionContext:
          type: object
          description: Execution context for the task
          additionalProperties: true
        metadata:
          type: object
          description: Additional metadata for the task
          additionalProperties: true
      required:
        - title
        - priority
        
    TaskStatusUpdate:
      type: object
      properties:
        status:
          type: string
          enum: [PENDING, IN_PROGRESS, COMPLETED, FAILED, CANCELED]
          description: New status for the task
        statusReason:
          type: string
          description: Reason for the status change
        progress:
          type: integer
          minimum: 0
          maximum: 100
          description: Current progress percentage (0-100)
      required:
        - status
        
    Workflow:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the workflow
        name:
          type: string
          description: Name of the workflow
        description:
          type: string
          description: Detailed description of the workflow
        status:
          type: string
          enum: [ACTIVE, PAUSED, COMPLETED, FAILED]
          description: Current status of the workflow
        tasks:
          type: array
          description: Tasks that are part of this workflow
          items:
            $ref: '#/components/schemas/Task'
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
      required:
        - id
        - name
        - status
        - createdAt
        - updatedAt
        
    WorkflowInput:
      type: object
      properties:
        name:
          type: string
          description: Name of the workflow
        description:
          type: string
          description: Detailed description of the workflow
        tasks:
          type: array
          description: Tasks to include in the workflow
          items:
            $ref: '#/components/schemas/TaskInput'
      required:
        - name 